// Fortune-cookie fortunes, grouped by topic.
export const FORTUNES = {
  wisdom: [
    "The journey of a thousand miles begins with a single step.",
    "A quiet mind hears what a busy one misses.",
    "The best time to plant a tree was twenty years ago. The second best time is today.",
    "Patience is not waiting; it is how you wait.",
    "He who asks a question is a fool for a minute. He who never asks is a fool forever.",
    "Still water runs deep. So do still people.",
    "You cannot pour from an empty cup. Fill yours first.",
    "The bamboo that bends is stronger than the oak that resists.",
    "Knowing others is intelligence; knowing yourself is wisdom.",
    "A small leak will sink a great ship. Mind the little things.",
    "The answer you seek is closer than the question you keep asking.",
    "Even the tallest mountain was climbed one step at a time.",
    "What you plant now, you will harvest later.",
    "The wise listen twice as much as they speak.",
    "Every master was once a beginner.",
    "Do not fear going slowly. Fear only standing still.",
    "Kindness is a language the deaf can hear and the blind can see.",
    "The obstacle in the path becomes the path.",
    "Silence is sometimes the best answer.",
    "A single conversation with a wise person is worth a month of study.",
  ],
  luck: [
    "Good news will come to you by mail.",
    "A pleasant surprise is waiting for you.",
    "Your luck is about to change for the better.",
    "Something you lost will soon turn up.",
    "An unexpected gift will brighten your week.",
    "The coin you find today is a sign of things to come.",
    "A lucky break is closer than you think.",
    "Fortune favors the bold, and today you are bold.",
    "Your lucky star is shining brightly tonight.",
    "The next door you knock on will open.",
    "Money will come to you from an unexpected source.",
    "You will be in the right place at the right time.",
    "A long-awaited answer will arrive soon.",
    "Today is a good day to take a chance.",
    "Good things come to those who wait, and better things to those who ask.",
    "Luck is on your side. Don't waste it on small bets.",
    "A stroke of good fortune is headed your way.",
    "The stars are aligned in your favor this week.",
    "What seemed like bad luck will turn out to be a blessing.",
    "Soon you will receive something you have wanted for a long time.",
  ],
  love: [
    "A thrilling romance is in your near future.",
    "Someone is thinking of you right now.",
    "The love you give away comes back to you twice.",
    "An old friend will soon bring new joy.",
    "Your heart knows the way. Let it lead.",
    "A smile from a stranger will make your day.",
    "The person you are waiting for is waiting for you too.",
    "Love is closer than you think. Look around.",
    "A kind word from you will mean more than you know.",
    "You will be loved for exactly who you are.",
    "A heartfelt letter will arrive when you least expect it.",
    "Your warmth draws people to you like a fire on a cold night.",
    "Tonight, call someone you miss.",
    "A new friendship will blossom into something lasting.",
    "The best relationships begin with a simple hello.",
    "Someone admires you from afar.",
    "Laughter shared is love multiplied.",
    "You will soon be reunited with someone dear to you.",
    "Open your heart and the right person will walk in.",
    "A small gesture of love will change everything.",
  ],
  work: [
    "Your hard work is about to pay off.",
    "A new opportunity will knock. Answer the door.",
    "Your talents will be recognized and rewarded.",
    "The project you started will bring great success.",
    "A promotion or new role is on the horizon.",
    "Your creativity will solve a problem others cannot.",
    "Today's effort is tomorrow's reward.",
    "A mentor will appear when you are ready.",
    "Your next idea will be your best one yet.",
    "Success is a journey, and you are well on your way.",
    "Someone important has noticed your good work.",
    "The deadline you fear will pass easily.",
    "A bold proposal will be well received.",
    "Your persistence will open doors that talent alone cannot.",
    "The skills you learn this year will serve you for life.",
    "An unfinished task will soon find its ending.",
    "Your leadership will inspire others.",
    "Great things have small beginnings.",
    "A difficult meeting will end better than you expect.",
    "The work you are proud of will outlast the work you rushed.",
  ],
  adventure: [
    "A journey to a faraway place is in your future.",
    "Say yes to the next invitation you receive.",
    "An exciting adventure awaits just around the corner.",
    "You will soon travel somewhere you have always wanted to go.",
    "Take the long way home. You'll be glad you did.",
    "A new path will reveal itself when you stop looking.",
    "The unknown is where your best stories begin.",
    "Pack light. Your next trip is closer than you think.",
    "Try something new this week. It will become a favorite.",
    "Adventure is not out there. It is in the way you look at things.",
    "A spontaneous decision will lead to a great memory.",
    "The map is not the territory. Go and see for yourself.",
    "You will meet someone interesting on a journey.",
    "Wander a little. Not all who wander are lost.",
    "Your courage will carry you further than you imagined.",
    "A sunrise in a new place is in your future.",
    "Step outside your comfort zone. The view is better.",
    "An unexpected detour will become the highlight of your trip.",
    "The road ahead is bright and full of surprises.",
    "Leave room in your plans for magic.",
  ],
};

export const TOPICS = Object.keys(FORTUNES);

// Six lucky numbers from 1 to 49, like the back of a real fortune cookie.
export function luckyNumbers() {
  const picks = new Set();
  while (picks.size < 6) picks.add(1 + Math.floor(Math.random() * 49));
  return [...picks].sort((a, b) => a - b);
}
